#!/bin/sh
# # x-r7rs -- the R7RS personality for x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus R7RS,
#   with no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"

# The x-r5rs bundle this one extends.  Sibling checkout by default; override
# with R5RS_ROOT for an installed tree.
# `|| true` because a failing command substitution inside an assignment is a
# failing assignment, and `set -e` then kills the script BEFORE the refusal
# below can print -- so a missing dependency reported itself as silence.
R5RS_ROOT="${R5RS_ROOT:-$(cd "$BUNDLE/../x-r5rs" 2>/dev/null && pwd || true)}"
if [ -z "$R5RS_ROOT" ] || [ ! -f "$R5RS_ROOT/r5rs/base.x" ]; then
	echo "x-r7rs: cannot find the x-r5rs bundle it extends" >&2
	echo "  looked for r5rs/base.x under ${R5RS_ROOT:-$BUNDLE/../x-r5rs}" >&2
	echo "  set R5RS_ROOT=/path/to/x-r5rs and retry" >&2
	exit 1
fi
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# WHICH x-base, and why it is not one path.  The contract says a bundle's
# harness loads boot/x-base.x -- the launcher-free AMALGAM, which carries no
# path literals and so loads from any cwd.  That is right, and "<root>/tests/
# works in both modes" holds for the runner.  It does NOT hold for the boot
# amalgams: an install has them at share/x/boot/, a checkout builds them into
# build/boot/, and <root>/boot/ exists in neither sense in a checkout.
#
# lib/x-base.x is NOT a substitute.  It is the SOURCE entry and opens with
# (include "lib/x-core.x") -- a root-relative literal that resolves only with
# the cwd at the repo root, which is exactly the addressing failure this
# bundle exists to not repeat.  Loading it from here fails with a bare
# "include: cannot open".
#
# So: probe, install layout first.  Reported upstream; collapse to one path
# if the layouts converge.
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-r7rs: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# Three things here are not obvious, and each costs an afternoon:
#
# 1. %install-root FIRST.  An amalgam carries no include literals, but its
#    deferred `import` forms resolve against the installed tree as it boots,
#    and module.x learns where that is from %install-root.  x.sh emits this
#    same line ahead of every boot entry; a harness loading an amalgam
#    directly has to emit it too.
#
# 2. boot/x-base.x, NOT a dialect entry.  he.x / xe.x / rn.x end with
#    (unless %batch? (do (%banner) (repl))) and would start a REPL underneath
#    the suite.  x-base.x is the launcher-free one, and being an amalgam it
#    carries no path literals, so it loads from any cwd.
#
# 3. NEVER re-include a platform module the tower already has.  The 2024
#    r7rs-base.x opened with (include "lib/x-core.x"); on top of a booted
#    tower that is a SEGFAULT with no diagnostic, not an error.  Deleting
#    that one line alone took the Kernel suite from dead to 68/72.  run.x owns
#    the boot; nothing under r7rs/ includes anything from the platform.
#
# The bundle root is armed the same way run.x arms it, so `import r7rs/base`
# resolves here exactly as it does at the prompt.
cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
(import-path! "$BUNDLE")
; BOTH ROOTS.  R7RS extends R5RS, so the harness arms the bundle it stands on
; before its own -- the same two-step run.x does, and the same gap: nothing in
; personality.xon declares the dependency (x-lang#526), so the path is probed.
(import-path! "$R5RS_ROOT")
(import r5rs/base)
(import r7rs/base)
(set! %repl-print %r7rs-repl-print)
EOF
