#!/bin/sh
# # x-r7rs -- the R7RS lang for x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus R7RS,
#   with no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# The required langs, read from the manifest. x.sh resolves (requires-lang ...)
# and arms each root before the bundle's own; the harness does not go through
# x.sh, so it repeats the resolution here, reading the same rows rather than
# hardcoding a name. Two spellings are probed because both layouts are real: an
# installed tree names the directory after the lang, a checkout after the
# repository. R5RS_ROOT overrides, for a tree elsewhere.
#
# The name only, version ignored: the row may carry a version, which x.sh
# checks against the `version` stamp an install or unpacked tarball carries. A
# sibling checkout has no stamp, and this harness exists to run against working
# trees, so enforcing the version here would make the suite unrunnable without
# installing first -- the same bypass --allow-lang-skew is. The pattern must
# not require ")" after the name, so a versioned row still matches.
DEP_ROOTS=
for _req in $(sed -n 's/^(requires-lang "\([^"]*\)".*/\1/p' "$BUNDLE/lang.xon"); do
	_root="${R5RS_ROOT:-}"
	if [ -z "$_root" ]; then
		for _c in "$BUNDLE/../$_req" "$BUNDLE/../x-$_req"; do
			if [ -f "$_c/lang.xon" ]; then _root="$(cd "$_c" && pwd)"; break; fi
		done
	fi
	if [ -z "$_root" ]; then
		echo "x-r7rs: lang '$_req' is required but not beside this bundle" >&2
		echo "  looked for $_req/ and x-$_req/ next to $BUNDLE" >&2
		echo "  it is declared by (requires-lang \"$_req\") in lang.xon" >&2
		exit 1
	fi
	DEP_ROOTS="$DEP_ROOTS $_root"
done

# Built before the heredoc rather than substituted inside it: an unquoted
# heredoc runs command substitution, and a printf carrying \n through one is
# a fight not worth having.
DEP_FORMS=
for _d in $DEP_ROOTS; do
	DEP_FORMS="$DEP_FORMS(import-path! \"$_d\")
"
done

# WHICH x-base, and why it is not one path.  The contract says a bundle's
# harness loads boot/x-base.x -- the launcher-free AMALGAM, which carries no
# path literals and so loads from any cwd.  That is right, and "<root>/tests/
# works in both modes" holds for the runner.  It does NOT hold for the boot
# amalgams: an install has them at share/x/boot/, a checkout builds them into
# build/boot/, and <root>/boot/ exists in neither sense in a checkout.
#
# lib/x-base.x is NOT a substitute.  It is the SOURCE entry and opens with
# (include "lib/x-core.x") -- a root-relative literal that resolves only with
# the cwd at the repo root, which is exactly the addressing failure this
# bundle exists to not repeat.  Loading it from here fails with a bare
# "include: cannot open".
#
# So: probe, install layout first.  Reported upstream; collapse to one path
# if the layouts converge.
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-r7rs: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# Three requirements on the generated file:
#
# 1. %install-root first. An amalgam carries no include literals, but its
#    deferred `import` forms resolve against the installed tree, which module.x
#    locates from %install-root. x.sh emits the same line ahead of every boot
#    entry.
#
# 2. boot/x-base.x, not a dialect entry. he.x / xe.x / rn.x end by starting a
#    REPL, which would run underneath the suite. x-base.x is launcher-free.
#
# 3. Never re-include a platform module the booted tower already has; on top
#    of a booted tower that crashes with no diagnostic. run.x owns the boot,
#    and nothing under r7rs/ includes anything from the platform.
#
# The bundle root is armed the same way run.x arms it, so `import r7rs/base`
# resolves here as it does at the prompt.
cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
$DEP_FORMS(import-path! "$BUNDLE")
(import r5rs/base)
(import r7rs/base)
(set! %repl-print %r7rs-repl-print)
EOF
